//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "PostLinks")]
pub struct Model {
    #[sea_orm(column_name = "Id", primary_key, auto_increment = false)]
    pub id: i32,
    #[sea_orm(column_name = "CreationDate")]
    pub creation_date: Option<DateTime>,
    #[sea_orm(column_name = "PostId")]
    pub post_id: i32,
    #[sea_orm(column_name = "RelatedPostId")]
    pub related_post_id: i32,
    #[sea_orm(column_name = "LinkTypeId")]
    pub link_type_id: Option<i8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::posts::Entity",
        from = "Column::PostId",
        to = "super::posts::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Posts2,
    #[sea_orm(
        belongs_to = "super::posts::Entity",
        from = "Column::RelatedPostId",
        to = "super::posts::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Posts1,
}

impl ActiveModelBehavior for ActiveModel {}
