//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

pub use super::badges::Entity as Badges;
pub use super::comments::Entity as Comments;
pub use super::post_history::Entity as PostHistory;
pub use super::post_history_type::Entity as PostHistoryType;
pub use super::post_links::Entity as PostLinks;
pub use super::post_type::Entity as PostType;
pub use super::posts::Entity as Posts;
pub use super::tags::Entity as Tags;
pub use super::users::Entity as Users;
pub use super::vote_type::Entity as VoteType;
pub use super::votes::Entity as Votes;

// Manual additions:
pub use super::post_tags::Entity as PostTags;
