//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Tags")]
pub struct Model {
    #[sea_orm(column_name = "Id", primary_key, auto_increment = false)]
    pub id: i32,
    #[sea_orm(column_name = "TagName")]
    pub tag_name: Option<String>,
    #[sea_orm(column_name = "Count")]
    pub count: Option<i32>,
    #[sea_orm(column_name = "ExcerptPostId")]
    pub excerpt_post_id: Option<i32>,
    #[sea_orm(column_name = "WikiPostId")]
    pub wiki_post_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
